[package]
name = "acralite"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.42"
askama = { version = "0.10.5", default-features = false }
async-trait = "0.1.51"
axum = { version = "0.1.1", features = ["headers"] }
bitflags = "1.2.1"
headers = "0.3.4"
hyper = { version = "0.14.11", features = ["http1", "http2", "runtime", "server", "tcp"] }
parking_lot = "0.11.1"
proguard = "4.1.1"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rand = "0.8.4"
refinery = { version = "0.6.0", features = ["rusqlite"] }
rusqlite = "0.25.3"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
serde_repr = "0.1.7"
tokio = { version = "1.9.0", features = ["fs", "macros", "parking_lot", "process", "rt", "signal"] }
toml = "0.5.8"
tower = { version = "0.4.8", features = ["timeout"] }
tower-http = { version = "0.1.1", features = ["compression", "decompression", "trace"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.19"

[profile.release]
lto = true
