[package]
name = "acralite"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.51"
askama = { version = "0.11.0", default-features = false }
async-trait = "0.1.52"
axum = { version = "0.4.3", features = ["headers"] }
bitflags = "1.3.2"
derive_more = "0.99.17"
headers = "0.3.5"
hyper = { version = "0.14.16", features = ["http2"] }
parking_lot = "0.11.2"
proguard = "4.1.1"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rand = "0.8.4"
refinery = { version = "0.7.0", features = ["rusqlite"] }
rusqlite = { version = "0.25.3", features = ["bundled"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
serde_repr = "0.1.7"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["fs", "macros", "parking_lot", "process", "rt", "signal"] }
toml = "0.5.8"
tower = { version = "0.4.11", features = ["timeout"] }
tower-http = { version = "0.2.0", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.3"

[profile.release]
lto = true
