[package]
name = "acralite"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.44"
askama = { version = "0.10.5", default-features = false }
async-trait = "0.1.51"
axum = { version = "0.2.8", features = ["headers"] }
bitflags = "1.3.2"
derive_more = "0.99.16"
headers = "0.3.4"
hyper = { version = "0.14.13", features = ["http2"] }
parking_lot = "0.11.2"
proguard = "4.1.1"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rand = "0.8.4"
refinery = { version = "0.6.0", features = ["rusqlite"] }
rusqlite = { version = "0.25.3", features = ["bundled"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_repr = "0.1.7"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["fs", "macros", "parking_lot", "process", "rt", "signal"] }
toml = "0.5.8"
tower = { version = "0.4.9", features = ["timeout"] }
tower-http = { version = "0.1.1", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.2.25"

[profile.release]
lto = true
