[package]
name = "acralite"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.56"
askama = { version = "0.11.1", default-features = false, features = ["with-axum"] }
askama_axum = "0.1.0"
async-trait = "0.1.52"
axum = { version = "0.4.8", features = ["headers"] }
bitflags = "1.3.2"
derive_more = "0.99.17"
headers = "0.3.7"
hyper = { version = "0.14.17", features = ["http2"] }
once_cell = { version = "1.10.0", features = ["parking_lot"] }
parking_lot = "0.12.0"
proguard = "4.1.1"
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
rand = "0.8.5"
refinery = { version = "0.8.4", features = ["rusqlite"] }
rusqlite = { version = "0.26.3", features = ["bundled"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_repr = "0.1.7"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["fs", "macros", "parking_lot", "process", "rt", "signal"] }
toml = "0.5.8"
tower = { version = "0.4.12", features = ["timeout"] }
tower-http = { version = "0.2.4", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
unidirs = "0.1.0"

[profile.release]
lto = true
