[package]
name = "acralite"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.62"
askama = { version = "0.11.1", default-features = false, features = ["with-axum"] }
askama_axum = "0.1.0"
async-trait = "0.1.57"
axum = { version = "0.4.8", features = ["headers"] }
bitflags = "1.3.2"
derive_more = "0.99.17"
headers = "0.3.7"
hyper = { version = "0.14.20", features = ["http2"] }
once_cell = { version = "1.13.1", features = ["parking_lot"] }
opentelemetry = { version = "0.17.0", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = { version = "0.10.0", features = ["trace"] }
opentelemetry-semantic-conventions = "0.9.0"
parking_lot = "0.12.1"
proguard = "5.0.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.19.0"
rand = "0.8.5"
refinery = { version = "0.8.6", features = ["rusqlite"] }
rusqlite = { version = "0.26.3", features = ["bundled"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_repr = "0.1.9"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["fs", "macros", "parking_lot", "process", "rt"] }
tokio-shutdown = "0.1.3"
toml = "0.5.9"
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.2.5", features = ["compression-gzip", "decompression-gzip", "trace"] }
tracing = "0.1.36"
tracing-opentelemetry = "0.17.4"
tracing-subscriber = "0.3.15"
unidirs = "0.1.0"

[profile.release]
lto = true
strip = true
