[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
exceptions = [
    { allow = ["MPL-2.0"], name = "option-ext" },
]

[licenses.private]
ignore = true

[bans]
skip = [
    "getrandom@0.2",
    "thiserror@1",
    "thiserror-impl@1",
    "wasi@0.11",
    "zerocopy@0.7",
]
skip-tree = [
    { crate = "windows-sys@0.52", depth = 3 },
    { crate = "windows-sys@0.48", depth = 3 },
]
