[advisories]
ignore = [
    "RUSTSEC-2020-0071",
    "RUSTSEC-2020-0159",
]

[licenses]
allow-osi-fsf-free = "either"
exceptions = [
    { allow = ["AGPL-3.0"], name = "acralite", version = "*" },
]

[bans]
skip = [
    { name = "itoa", version = "=0.4.8" },
]
